/*
* generated by Xtext
*/
package org.casualintellect;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CasualIntellectUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.casualintellect.ui.internal.CasualIntellectActivator.getInstance().getInjector("org.casualintellect.CasualIntellect");
	}
	
}
